# Why Quarto

{{< include slides/_content-value-chain.qmd >}}

{{< include slides/_literate-programming.qmd >}}

{{< include slides/_tools-for-literate-programming.qmd >}}

{{< include slides/_intro_quarto.qmd >}}

<!--
{{< include slides/_population-project-challenges.qmd >}}
-->

# Quarto workflow

{{< include slides/_ipynb-pipeline.qmd >}}

{{< include slides/_quarto-ipynb-pandoc.qmd >}}

# Using Quarto

{{< include slides/_yaml-front-matter.qmd >}}

{{< include slides/_quarto-main-content.qmd >}}

{{< include slides/_code-content.qmd >}}

{{< include slides/_diagrams.qmd >}}

{{< include slides/_tables.qmd >}}

# Presentations in Quarto

{{< include slides/_basic-slide-syntax.qmd >}}

{{< include slides/_powerpoint-slides.qmd >}}

{{< include slides/_powerpoint-layout-rules.qmd >}}

{{< include slides/_powerpoint-templates.qmd >}}

{{< include slides/_generating-content-dynamically.qmd >}}

# Generating a website

{{< include slides/_changing-format-to-website.qmd >}}

{{< include slides/_presentation-screenshot.qmd >}}

# Scholarly articles

{{< include slides/_writing-articles.qmd >}}

{{< include slides/_articles-screenshots.qmd >}}

{{< include slides/_citations-footnotes.qmd >}}

{{< include slides/_cross-references.qmd >}}

# Books in Quarto

{{< include slides/_books.qmd >}}

# Should I use Quarto?

{{< include slides/_should-i-use-quarto.qmd >}}

# Where to go next

{{< include slides/_next-steps.qmd >}}

::: {.content-visible unless-format="pptx"}
{{< include slides/_hacks.qmd >}}
:::

::: {.content-visible when-format="pptx"}
## Hacks

Quarto is under active development, and quickly reaching v1.0. While creating this content, I had to do some workarounds.

1. I created a [script](https://github.com/quarto-dev/quarto-cli/discussions/1232) to quickly install the latest version
2. Mermaid diagrams blank in PPTX. [Bug](https://github.com/quarto-dev/quarto-cli/issues/1159) quickly fixed.
3. Mermaid diagrams blank in RevealJS. Workaround: refresh.
4. HTML website and RevealJS from same source: images disappear
    - Workaround: add `self-contained: true` to YAML front-matter
5. Pandoc large monospaced font size in PowerPoint. Workaround: [script](https://github.com/quarto-dev/quarto-cli/discussions/1272).
6. The decorations on this slide only appear on RevealJS, by design.
7. Slide with article screenshots renders weird in HTML, no workaround.

:::

