project:
  type: website
  output-dir: docs
  post-render: ./post-render.sh

website:
  title: "Using Quarto for Everything"
  google-analytics: "G-6KTZ853BN5"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
