project:
  type: website
  output-dir: docs
  post-render: ./post-render.sh

website:
  title: "Using Quarto for Everything"
  google-analytics: "G-6KTZ853BN5"
  navbar:
    left:
        - text: "Using Quarto: Home"
          file: index.qmd
        - text: "Blog"
          href: https://www.meyerperin.com/
        - text: "GNNs with Python"
          href: https://www.meyerperin.com/python-gnn
        - text: "Econometrics with Python"
          href: https://www.meyerperin.com/econometrics-python
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/lucasameyer
      - icon: github
        href: https://github.com/lucas-a-meyer
      - icon: twitter
        href: https://twitter.com/lucas_a_meyer
      - text: "About"
        href: https://www.meyerperin.com/about.html

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
