---
title: "Quarto with Python"
include-in-header: _msft-clarity.html
author: Lucas A. Meyer
date: 2022-07-07
self-contained: true
---

```{python}
#| echo: false
from IPython.display import display, Markdown
from itertools import chain
import pandas as pd
```

{{< include _graph_functions.qmd >}}


Folowing the spirit of ["learning out loud"](https://www.meyerperin.com/2019-02-13-why-you-should-blog-if-you-are-a-data-scientist.html), I created several artifacts while I was learning about [Quarto](https://www.quarto.org). 

I created one main content file [(source)](https://github.com/lucas-a-meyer/using-quarto/blob/main/_presentation-content.qmd) that imports lots of other topic-based [files](https://github.com/lucas-a-meyer/using-quarto/tree/main/slides), to create:

- A RevealJS [presentation](/presentation.html)
- A [PowerPoint presentation](/presentation.pptx) that uses my team's template
- This website, starting after the "Why Quarto" header below [(source)](https://github.com/lucas-a-meyer/using-quarto/blob/main/index.qmd)

I also reused some of the content above in another Quarto file [(source)](https://github.com/lucas-a-meyer/using-quarto/blob/main/article.qmd) to create:

- A scholarly-looking [article](/article.pdf) in PDF using LaTeX
- A scholarly-looking [document](/article.docx) using Microsoft Word

The content below tells why I chose Quarto and how I use it with Python.

{{< include _presentation-content.qmd >}}

## Mixing R and Python

I also created an R [source](https://raw.githubusercontent.com/lucas-a-meyer/using-quarto/main/computations.qmd) file (copied directly from the Quarto tutorial) and added it to this project. Quarto does not allow the same file to run Python and R, but allows two different files. The result of the R source is [here](computations.qmd).